# Generated by Django 5.0.7 on 2024-08-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='COLOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CONDITION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title1', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('button_tag', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='slider_image/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='slider_image1/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='slider_image2/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='slider_image3/')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prev_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.TextField()),
                ('top_seller', models.BooleanField(default=False)),
                ('deals_of_the_day', models.BooleanField(default=False)),
                ('trending_product', models.BooleanField(default=False)),
                ('featured_product', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('wish_list', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.category')),
                ('color', models.ManyToManyField(to='LetsShop_App.color')),
                ('condition', models.ManyToManyField(to='LetsShop_App.condition')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size', models.ManyToManyField(to='LetsShop_App.size')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.subcategory')),
            ],
        ),
    ]
