# Generated by Django 5.0.7 on 2024-10-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.subcategory')),
            ],
        ),
    ]
