# Generated by Django 5.0.7 on 2024-08-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_Accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
