# Generated by Django 5.0.7 on 2024-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_Accounts', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
